default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: grill_master_development
  host: localhost
  port: 5432
  username: rails_dev
  password: rails_dev_pass

test:
  <<: *default
  database: grill_master_test

production:
  <<: *default
  database: grill_master_production
  username: grill_master
  password: <%= ENV['GRILL_MASTER_DATABASE_PASSWORD'] %>
